//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::bookings::Entity as Bookings;
pub use super::guests::Entity as Guests;
pub use super::hotels::Entity as Hotels;
pub use super::rooms::Entity as Rooms;
